### ISSUE TITLE
Lead time scatter chart incorrectly plotting

### ISSUE THREAD

**Issue by iand123** [nbrown02/FlowViz-Jira#14]
Hey Nick

Have been testing out and think ive stumbled across a bug on the lead time chart. It seems it is grouping it by the lead time and not by the completed date. As you can see from the screenshots, the cycle time has a much more consistent scatter of items being compelte. Id you look at the lead time scatter its much more sparse. The larger screenshot shows the plot for one item that all have 34 days as the lead time but have different completed dates. Should these not be plotted for each day they are completed?

Hope that makes sense, if not let me know and ill try to explain is a clearer way!

![Screenshot 2022-07-25 at 15 11 08](https://user-images.githubusercontent.com/10867134/180798513-6dead924-f086-482f-9323-9df6b3cd3150.png)
![Screenshot 2022-07-25 at 15 10 20](https://user-images.githubusercontent.com/10867134/180798519-65f3a515-3eff-4806-85b9-b9686fce0619.png)

**Comment by iand123** [comment]
Should add, i dont believe ive done anything to edit the visual! WHilst i have been hacking around with other stuff like adding an itemtype slicer and making it work across project i havent touched the visuals :)

**Comment by iand123** [comment]
Ok so i think i found the issue. Looking at the lead time scatter it was sum'ing on the Days since completed field on the x-axis. If you remove that then it seems to show data much more as i would expect. More screenshots below :)


![Screenshot 2022-07-25 at 15 26 18](https://user-images.githubusercontent.com/10867134/180801189-0406cb3e-3ab3-489b-b373-dbdef3b525d3.png)

![Screenshot 2022-07-25 at 15 26 34](https://user-images.githubusercontent.com/10867134/180801181-4f8601bd-c1f2-4d3a-ac14-8ce2feda7ba9.png)

**Comment by nbrown02** [comment]
Ahhh good spot - this is the problem of having a rubbish test instance with like 4 stories on it :D 

Thank you - will fix and upload!

P.s. 'Absence' issue type has me curious :D

**Comment by iand123** [comment]
@nbrown02 yep, dont get me started on that one, only just found it. Need to do some exploring but yeah that was a facepalm moment

**Comment by iand123** [comment]
So its actually fairly innocent, a card on the board that represents any in sprint known absence. I guess its better than it being a story (and then being included in any cycle time/lead time data)

Back in the day when we were all in the same room youd just write it next to the board but Jira (and other tools) has no way of doing that.

I was worried at first that it was tracking people absence

**Comment by iand123** [comment]
@nbrown02 yeah exactly. Given you now work where i used to work you'll probably be seeing the amount of similar things like retro actions coming through in the data in ADO :) Guess its better these things are not separate and classed as user stories

Always say with these things, people expect metrics to give you answers as i find it just leads to you asking more questions/having more conversations. thats where the value lies

**Comment by nbrown02** [comment]
Ha - there actually aren't many things I've seen so far that have confused me, so looks like we were aligned in ADO usage :)

Precisely - one thing we're doing is taking blockers further actually with noting down the reason why (custom field or in the tags themselves):

![image](https://user-images.githubusercontent.com/29369962/180815563-1cb93fe5-00f6-46f5-9d23-b0c1e7eda5dd.png)

We're hoping that leads to some better questions...

**Comment by iand123** [comment]
Thats a really cool visualisation, as i replied on the discussion thread we are currently working that out ourselves to be able to firstly consistently capture blockers in the same way but will lead to a conversation about classification of them too

**Comment by nbrown02** [comment]
Fixed in the latest version just deployed :)
