### ISSUE TITLE
Net flow drill through not showing the right data?

### ISSUE THREAD

**Issue by iand123** [nbrown02/FlowViz-Jira#15]
Me again, sorry 😂

See the attached screenshots for examples. When i drill through to look at a week on the sustainability (new flow) visual whilst the compelted vs started visual seems correct the summary data below is always the same for started vs finished. Have tried multiple weeks in different teams and cant get anything but those two data tables being the same thing
![Screenshot 2022-07-25 at 16 23 09](https://user-images.githubusercontent.com/10867134/180815781-515d8a1a-b365-4b77-96dd-ec0e93c531f9.png)
![Screenshot 2022-07-25 at 16 22 58](https://user-images.githubusercontent.com/10867134/180815790-a5a6b5a2-a8d5-491e-ba63-4622b53f425b.png)
![Screenshot 2022-07-25 at 16 22 46](https://user-images.githubusercontent.com/10867134/180815791-aad13dc7-5d1a-4051-9aa7-3495b9277181.png)

**Comment by nbrown02** [comment]
Hmm yeah doesn't look right. Let me do some digging again and try fix.

Keep the feedback coming! Built this using very small datasets and only a few Jira teams here for me to validate against!

**Comment by iand123** [comment]
Ive got over 5000 work items now as ive opened it up across project so hopefully getting a lot of data. Will keep an eye out for anything else as i have a play around

**Comment by nbrown02** [comment]
Fixed in the latest version just deployed :)

**Comment by iand123** [comment]
ANy idea what the fix was? Trying to minimise having to redo all of my hacking :D

**Comment by nbrown02** [comment]
Ha! So you need to drag in the IssueID and InProgressDate from the 'WorkItems History3' table (previously I was using the wrong one) into the visual for Started This Week. 
<img width="357" alt="Screenshot 2022-07-25 at 17 42 33" src="https://user-images.githubusercontent.com/29369962/180830849-055d390d-3d7c-40aa-9318-9776d12acb19.png">



If you want to make the IssueID into a URL, then you need to use cell elements and conditional formatting for the URL column...
<img width="164" alt="Screenshot 2022-07-25 at 17 42 12" src="https://user-images.githubusercontent.com/29369962/180830838-e25d768f-bc03-4caa-a72c-a73b0ae03782.png">

**Comment by iand123** [comment]
Thanks for this Nick. Have added those and its working but the date format seems slightly different (see screenshot). Looking in the model the InProgressDate field has it in WorkItemsHistory3 has the extra formatting that it doesn't have in WorkItemsHistory (which as far as i can work out is a copy of that table with extra processing). Is it safe to format that field in that table to just be dd-MM-yy?
![Screenshot 2022-07-26 at 09 10 02](https://user-images.githubusercontent.com/10867134/180956829-0e2b9b73-7807-45fc-85bf-00dc20c5d08f.png)

**Comment by nbrown02** [comment]
D'oh knew there was something I missed - yeah exactly that, just change it to that format :)

**Comment by iand123** [comment]
Awesome, thanks for confirming (and for the help and making this in the first place - how do i send you a virtual beer?)

**Comment by nbrown02** [comment]
Ha! I should thank you for finding the bugs, I think people just assume it is bug free :D 

A review on the [Atlassian](https://marketplace.atlassian.com/apps/1227910/flowviz?hosting=cloud&tab=overview) or [Microsoft](https://marketplace.visualstudio.com/items?itemName=agile-extensions.flowviz) marketplace would be great if you have the time :)
