### ISSUE TITLE
Average cycle time graph on dashboard not matching the date slicer

### ISSUE THREAD

**Issue by iand123** [nbrown02/FlowViz-Jira#16]
Hey Nick

Playing around some more and found a bug. I have set it to the last 52 weeks but the cycle time graph on the dashboard only goes back to feb this year (6 months or so). AM i missing something? all the others seem to work to that slicer

![Screenshot 2022-07-29 at 15 38 41](https://user-images.githubusercontent.com/10867134/181783965-81530d3e-e8ca-4123-b4b7-0140a76003d3.png)

**Comment by iand123** [comment]
Which weirdly correlates to sometehing else i am seeing. Looked at the net flow graph across the last year for all teams just to see what it told me. In doing so the general trend was that we were starting more work than finishing it compared to the previous part of the year (see below)

at around the same time that the cycle time graph will start to work we also see the trend suddenly changing. I wonder if there is either a data issue at play or something a bit weirder?


![Screenshot 2022-07-29 at 15 42 55](https://user-images.githubusercontent.com/10867134/181784783-5eec925a-4dd4-4b37-8dab-bfbe62eab8ad.png)
![Screenshot 2022-07-29 at 15 42 36](https://user-images.githubusercontent.com/10867134/181784799-5cfd6e03-3e06-4976-a777-74e621d3adab.png)

**Comment by iand123** [comment]
I may have found the issue! Looking at the queries the querty for WorkItems History seems to only pull back 26w of data as where the others all seem to work for 52

code snippet here 

"/rest/api/2/search?jql=project%20in%20(" & #"Project Key" & ")%20AND%20statusCategory%20in%20(4%2C%203)%20AND%20statusCategoryChangedDate%20%3E%3D%20**-26w**%20AND%20hierarchyLevel%20%3D%200%20order%20by%20created%20DESC&expand=changelog"

**Comment by iand123** [comment]
I think (and please correct me if i am wrong) the issue in net flow is caused because in the WorkItemsHistory3 table the completed1 and started1 fields are calculated from different data tables

Started1 = COUNTROWS(GROUPBY('WorkItems History3','WorkItems History3'[InProgressDateSK],'WorkItems History3'[IssueID]))

Completed1 = IF(ISBLANK(count('WorkItems Completed'[CompletedDateSK])),0,(count('WorkItems Completed'[CompletedDateSK])) )

WorkItems History3 is a clone on WorkItems History which is hardcoded in the query URL to have 26w of data as where WorkItems Completed has 52w of data hence meaning there is more data for completed until the 26w of data kicks in.

Far from me to suggest fixes but would it need to either

1. Have 52w of data in each source
2. Calculate the started1 and completed1 fields from the same table

Hopefully some of this makes any sense :)

**Comment by nbrown02** [comment]
Hey Ian,

Yup - all makes sense :) 
The 26 weeks data limit is by design, as to calculate the cycle time I need to pull through all status changes (this is where the API is less friendly than the AzDO one!). Quicker fix is suggestion 1 - I'll make that change now 👍

**Comment by nbrown02** [comment]
All fixed :)
