### ISSUE TITLE
Project slicer not working

### ISSUE THREAD

**Issue by dtlo** [nbrown02/FlowViz-Jira#23]
I am using the multiple project version.
The slicer on the top of the report pages is using the field "WorkItems IssueType.WorkItems History2_ProjectName", but there is no relation to any table from "WorkItems IssueType". As fare as I understand, thats the reason why it is not filtering the visuals on any report page.
![image](https://github.com/nbrown02/FlowViz-Jira/assets/42714462/e8b74f7e-9b8b-4a5e-b24e-b2ca9ee14d34)

**Comment by nbrown02** [comment]
Hi there - is this for the [Azure DevOps version of the template](https://github.com/nbrown02/FlowViz)? That table does not exist in the Jira version?

**Comment by dtlo** [comment]
Hi - it is in "FlowViz (Jira - Multiple Projects).pbit", the latest version from 8 June. Its an computed DAX table if that is helping?
![image](https://github.com/nbrown02/FlowViz-Jira/assets/42714462/b0ffb4e3-75c5-4308-beb3-a34bf53cc4c0)

**Comment by nbrown02** [comment]
Ah ok - can you try the version from this commit New version ·
***@***.*** (github.com)
<https://github.com/nbrown02/FlowViz-Jira/commit/96ffc6d4b7f7f76f4c3509145bd7dc41c97fe973>
 ?

**Comment by dtlo** [comment]
Perfect - filter now works for me as expected - thanks for the quick fix!

**Comment by nbrown02** [comment]
No worries! Thank you for sharing :)
