### ISSUE TITLE
app.powerbi.com crashes with D3JSVisual

### ISSUE THREAD

**Issue by kfurgerot** [nbrown02/FlowViz-Jira#25]
When i upload the dashboard to Microsoft Online powerbi services, the forecast tab make the browser crash.
I think the problem comes from the D3JSVisual visual 

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/126aefb0-dae3-4af5-952f-a9dfb753e9e4)

**Comment by nbrown02** [comment]
Just tried it on my reports and not seeing this issue. I'd suggest it is
most likely due to the amount of data being loaded/forecasted against.

A workaround could be to turn on 'sync slicers' and ensure you filter on a
project before loading that page?

**Comment by kfurgerot** [comment]
@nbrown02 , thank you for your answer.
When i open the console on Chrome i have these errors

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/2feef226-39cb-4ac3-805d-b921e4455d0e)

But i don't know really what it meens

**Comment by kfurgerot** [comment]
On Desktop it works without problems

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/1f20351d-92b4-49a6-b6e8-827f7b0cf936)

**Comment by nbrown02** [comment]
Struggling with what the issue may be - it works fine on all reports I am
using and not seeing this with other users. Suggest logging issue with
Microsoft as it seems to be related to Power BI web service...

**Comment by kfurgerot** [comment]
Nicolas,

We founded the issue with Microsoft Support.
it was the licence on the workspace, it was not set to "Pro"

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/e329b428-cbce-4b66-9894-14c4f4f2d4d0)

**Comment by nbrown02** [comment]
So is it now working (and can this be closed) ?

**Comment by kfurgerot** [comment]
Yes ! :)
