### ISSUE TITLE
Cycle on Bug issues

### ISSUE THREAD

**Issue by kfurgerot** [nbrown02/FlowViz-Jira#27]
Hi,

Cycle time seems to be wrong on issuetype "Bug".
When a Bug is starting, cycle time assume the work is done.
It seems to be OK on Story issue but the calculation seems ko on bug issue
On jira board the status "Correction en cours" is not the last column "Done"

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/c7c8354a-a911-4650-aa15-280f8c04c617)

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/344a4399-ab18-48d6-bb58-262d014d3261)

**Comment by nbrown02** [comment]
Ignore my comment - I've spotted the issue. Try [the latest version](https://github.com/nbrown02/FlowViz-Jira/raw/main/FlowViz%20(Jira).pbit) and close if it's resolved :)

**Comment by kfurgerot** [comment]
@nbrown02 Thank you :) 

i will try it when i will come back from my holidays :)

Regards

Karl

**Comment by kfurgerot** [comment]
I have download your latest version and after a quick look it seems to be better :)
I m sorry but i can't confirm right now it s totaly resolved :(

**Comment by nbrown02** [comment]
Closing as this is fixed.
