### ISSUE TITLE
Done state on cycle time scatter plot

### ISSUE THREAD

**Issue by kfurgerot** [nbrown02/FlowViz-Jira#30]
Hi,

On the cycle time scatter plot, some issues are considered as done but it's not the right.

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/e2efaf6e-6afa-4719-a07e-85c38c966da3)

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/bde849b3-79e0-4c00-995a-8ef66248185a)

Thank you.

Regards

**Comment by nbrown02** [comment]
Hey Karl,

Can you share the state history of that item from Jira? Was it ever in a 'done' state?

Thanks,

Nick

**Comment by kfurgerot** [comment]
Hi @nbrown02,

Yes here the screenshot

![image](https://github.com/nbrown02/FlowViz-Jira/assets/14217656/c89829f2-94c5-403e-81ed-107badffddcc)

Regards

Karl FURGEROT

**Comment by nbrown02** [comment]
Thanks - and what is the date it is saying it was completed?

Can you also confirm this is the latest version of the template?

Thanks again

**Comment by kfurgerot** [comment]
It says it done on the 02 november.
yes i used the last one :)

**Comment by nbrown02** [comment]
I'm not sure how this is possible, _WorkItems History_ (which is the table this chart sits behind) only ever queries items in the 'Done' status category...not seeing this on any other reports or able to reproduce :/
