### ISSUE TITLE
Jira API responds with 400 bad request 

### ISSUE THREAD

**Issue by MaximumTrainer** [nbrown02/FlowViz-Jira#31]
Since 28th November the flowviz jira connection responds with 400 error from power bi, the same JQL works correctly via browser or curl indicating there is an issue with the dashboard. 
This is the same for my customised solution & the vanilla download from github.

**Comment by nbrown02** [comment]
Hi there,

I have just loaded data perfectly fine for a number of projects, I also have no refresh failed errors on any of my reports in the web service (examples attached):

![refrsh2](https://github.com/nbrown02/FlowViz-Jira/assets/29369962/fbeb154f-5afe-4983-aa3d-8d58b4e6881a)

![refrsh1](https://github.com/nbrown02/FlowViz-Jira/assets/29369962/8218580b-0f76-4d48-ad09-761003fbdd4b)

So can't see any issues related to the dashboard...

**Comment by MaximumTrainer** [comment]
thanks thats useful, it must be an issue with my particular jira instance.

**Comment by nbrown02** [comment]
With bigger projects it can take a while I find, but not seeing any 400
errors :)

**Comment by MaximumTrainer** [comment]
Thanks. This was an issue within our environment. all resolved now

**Comment by nbrown02** [comment]
Glad to hear, thanks for letting me know :)
