### ISSUE TITLE
API token

### ISSUE THREAD

**Issue by tomramsay** [nbrown02/FlowViz-Jira#32]
Hi Nicolas 
   
In the Jira Flowvis instructions, you referred to generating an API token, but I'm unclear about where to use it when connecting PowerBI to Jira. It's possible that there's a permissions issue, as I'm encountering a (400): Bad Request error while trying to set up the template. Could you possibly know why this is happening? I've completed all the prerequisites, except for understanding the application of the API token after its creation.

Regards 

Tom

**Comment by tomramsay** [comment]
Manage to figure out how to use the API token, might be worth adding this to the instructions:

Create an API Token in Jira:

Log into your Atlassian account.
Navigate to the API token section (usually under Account settings or Security settings).
Create a new API token. Once it's created, make sure to copy it and store it securely.
Use the API Token in Power BI:

Open Power BI and go to the section where you are setting up the data source connection to Jira.
When prompted for authentication, select "Basic" as the authentication method.
In the username field, enter the email address associated with your Atlassian account.
In the password field, use the API token you generated in Jira. (Do not use your Atlassian account password).
Complete the Connection:

After entering your email and API token, proceed to connect.
Power BI should now authenticate using these credentials and fetch data from Jira.

**Comment by nbrown02** [comment]
Hi @tomramsay 

Thanks for sharing. Out of interest, what were you using as your setup instructions? Only because I believe all this info/detail is documented already in the readme for the repo? 😅
