### ISSUE TITLE
[Suggestion] Option for "Forecast" to select only backlog items placed in a certain sprints

### ISSUE THREAD

**Issue by svscorp** [nbrown02/FlowViz-Jira#34]
Idea/Suggestion.

Currently, the entire backlog (all sprints and "Backlog") is calculated in forecasting. I am wondering, would it be possible to add a dropdown to select sprints and "backlog" to be included in the calculation. What I am trying to achieve is to forecast only selected sprints (not all) delivery forecast. And why "selected" - because some of the sprints are rather used as a "container" for wishes and desires, that are stretch. Backlog contains all the ideas that keep continuously coming.

**Comment by nbrown02** [comment]
Unfortunately there is no field for 'sprints' to use which is universal to all Jira projects...

![image](https://github.com/nbrown02/FlowViz-Jira/assets/29369962/1fabbef3-27cc-4ba3-b005-e88dae16dfe4)

The info is likely there, it will probably be one of the 'customfield_xxxxx' values:

![image](https://github.com/nbrown02/FlowViz-Jira/assets/29369962/c7933c15-2c6c-4d24-976c-e6ab6899e52e)

However these are not the same across Jira projects, so wouldn't work in a template like this - so won't be looking to add this

**Comment by nbrown02** [comment]
As I try to keep the template as framework agnostic as possible, I won't be looking to implement it. However if you do find a way to do it yourself it would be great if you could show others using the [discussion section](https://github.com/nbrown02/FlowViz-Jira/discussions). If you just pose it as a question then post the answer I can mark it as the answer :)
