### ISSUE TITLE
Forecast - "What will we get?" doesn't render chart if 10 or more weeks is selected to forecast

### ISSUE THREAD

**Issue by svscorp** [nbrown02/FlowViz-Jira#35]
After the data is loaded, all the charts are working fine. It is discovered, while playing with different available for change parameters, on the Forecast Data - I select "200 items to forecast" (in the top chart) and then Number of weeks to forecast: 10 - so from 10 and above, the bottom chat "What will we get?" doesn't show anything.

9 weeks
![image](https://github.com/nbrown02/FlowViz-Jira/assets/475464/306aa177-6439-4b97-bc1e-958c35b9ca9e)

10 weeks
![image](https://github.com/nbrown02/FlowViz-Jira/assets/475464/5ed7104e-9828-41d1-ab63-d0e42f982a9a)

**Comment by nbrown02** [comment]
This is because the chart is unreadable based on the information selected - unfortunately there is no way around this unless you filter your input data somehow...

**Comment by svscorp** [comment]
@nbrown02 thanks. What do you mean by filtering the amount of data being used for it to work, and what/where is required to be changed? In my case there are 800+ current backlog size and on the top chart, regardless what I select (number of items to forecast) situation on the bottom graph is not changing. However, I think that dropdown is intended to affect only the top chart...

In addition to the clarification question, I have the second one - is there a reason for limiting "number of items to forecast" to 250 and not to "current backlog size"?

**Comment by nbrown02** [comment]
So I believe whenever a filter is made to the forecast page, the forecast reruns (even if the inputs haven't changed). I know that slicer does not filter that chart so nothing more from a building perspective I can do. I am however working on some code changes to the D3 (should be pushed out tomorrow) which might make this go away.

I set it to 250 as I couldn't imagine any team having a backlog bigger than that/wanting to forecast that many. A backlog of 850 items seems incredibly high. If you want to change it all you need to do is change the 250 value in the number of items to forecast table...

**Comment by nbrown02** [comment]
@svscorp check the latest release to see if it improves this for you

**Comment by svscorp** [comment]
I will check, opening latest PowerBI template file would be just fine (there is no historical data saved/maintain, right)? Not sure if template is fully ephemeral. @nbrown02

**Comment by svscorp** [comment]
And thank you!

**Comment by nbrown02** [comment]
Nope just new file and reconnect, unfortunately no other way to roll it out to users :(

**Comment by nbrown02** [comment]
There were no plans to change this - see the release notes for what was changed
