### ISSUE TITLE
Error: We could not convert null to text

### ISSUE THREAD

**Issue by ighilr** [nbrown02/FlowViz-Jira#39]
Hello,
Thank you for the excellent work but especially for sharing your project.
However, I have a problem when using the report for the first time. I get errors: "Sorry... We could not convert null to text". Do you have a solution please?  No metrics work in the report.
![image](https://github.com/nbrown02/FlowViz-Jira/assets/40204485/b1be7a25-ac66-4684-8860-1ee5040e1ab3)

Thanks

**Comment by ighilr** [comment]
Thanks for your feedback. Is it mandatory to have a PowerBI Pro license and/or be connected? I tried to analyze all possible root causes, to no avail :/

**Comment by nbrown02** [comment]
No it will work in Power BI Desktop just fine. Might be we need to have a call so I can see your Jira setup...

**Comment by ighilr** [comment]
Thank you for the answer. I managed to resolve this issue. Now I have another error message: Access to the resource is prohibited. While my email address is correct, I have generated API token and I have access to the project as well as the API outside of PowerBI. Perhaps a protection from our Jira admins, I work in a large organization.
![image](https://github.com/nbrown02/FlowViz-Jira/assets/40204485/cdd317ad-ec3b-42c0-921e-2e51daecccad)

**Comment by nbrown02** [comment]
Ah good to hear. 

That I am not too sure about because I'm not sure they even can lock that down? Maybe try another access token? I'm assuming you are using the email associated with your Jira instance as user name and the API token in your password (choosing "Basic" as login type) ?

**Comment by ighilr** [comment]
Yes I use everything you mentioned. I followed your documentation carefully. I created and revoked several tokens, to no avail. I'm going to see the admins of our Jira instance tomorrow. I'll keep you informed :)
Thank you for everything !

**Comment by ighilr** [comment]
Hello :)
I come with news. I checked with the Jira Admins. No worries or overprotection on our instance.

I feel like Basic Auth mode isn't working at all, because I managed to call our Jira API via a blank PowerBI report. 

I put the URL of our Jira, add an Authorization parameter: Bearer TOKEN API
and Content-Type: application/json, this downloads the data.

I saw this solution in this post where other people had the problem: https://community.atlassian.com/t5/Marketplace-Apps-Integrations/How-to-connect-Power-BI-to-JIRA -using-Rest-API-and-without-third/qaq-p/2255960

However, I'm having trouble doing the same thing on your report.

**Comment by nbrown02** [comment]
I've tried 3-4 times different access tokens with basic login and all
working fine for me - really not sure what the issue could be :/

**Comment by ighilr** [comment]
Hello :)
After several tests in PowerBI and Postman. I think I have a clue... I have this message: `{
    "errorMessages": [
        "Field 'hierarchyLevel' does not exist or you do not have permission to view it."
    ],
    "errors": {}
}`
Searching and looking in the Jira API documentation, it seems that this field is deprecated so that's why I can't find it. Maybe we are not on the same versions of Jira, which explains why it works for you. I tried other fields such as parentId but it doesn't seem to work.

**Comment by nbrown02** [comment]
Ahhh that makes more sense as I remember changes around epic link/parent.
Can you send me a link to that documentation? I wonder if there is a 'new'
field name I should use...

**Comment by ighilr** [comment]
Ah, I'm reassured that this means something to you because I'm really struggling... :D

Here's where I saw the field was deprecated: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-hierarchy-levels/

**Comment by ighilr** [comment]
![image](https://github.com/nbrown02/FlowViz-Jira/assets/40204485/4d3459ea-2972-4cf9-bf3e-15dc6da59edc)
Indeed... I don't understand anything anymore :( Here is the Postman capture, I have the same error on PowerBI

**Comment by nbrown02** [comment]
What happens when you remove “hierarchylevel” from the query?Sent from my iPhoneOn 7 Jun 2024, at 14:43, GitPassion ***@***.***> wrote:﻿
image.png (view on web)
Indeed... I don't understand anything anymore :( Here is the Postman capture, I have the same error on PowerBI

**Comment by ighilr** [comment]
If I remove "hierarchylevel", I get an OK 200 response
![image](https://github.com/nbrown02/FlowViz-Jira/assets/40204485/224da8bb-139b-4b30-a564-89a66f7779a4)

**Comment by ighilr** [comment]
I have the same error for the field : "statusCategoryChangedDate"
`{
    "errorMessages": [
        "Field 'statusCategoryChangedDate' does not exist or you do not have permission to view it."
    ],
    "errors": {}
}`

**Comment by nbrown02** [comment]
It must be a permissions thing - there’s simply no way your Jira instance would work without this field. The template also wouldn’t work even if it would connect. Sent from my iPhoneOn 7 Jun 2024, at 16:32, GitPassion ***@***.***> wrote:﻿
I have the same error for the field : "statusCategoryChangedDate"
{ "errorMessages": [ "Field 'statusCategoryChangedDate' does not exist or you do not have permission to view it." ], "errors": {} }

**Comment by ighilr** [comment]
That's what I tell myself too... I asked our Jira admins to add these two fields for reading in our API. I'm waiting and hoping to hear back on Monday...
Thank you in any case for your feedback and your patience.

Have a nice week end

**Comment by nbrown02** [comment]
Thanks keep me posted - same to you!Sent from my iPhoneOn 7 Jun 2024, at 17:06, GitPassion ***@***.***> wrote:﻿
That's what I tell myself too... I asked our Jira admins to add these two fields for reading in our API. I'm waiting and hoping to hear back on Monday...
Thank you in any case for your feedback and your patience.
Have a nice week end

**Comment by ighilr** [comment]
Hello :)
I have received feedback from the Jira Admin, they tell me that the missing fields are accessible in the Cloud version. Our company works on a Server instance...

**Comment by nbrown02** [comment]
Ah then this isn't something I can really help with - the repo (and
listing) mention only Jira cloud...

**Comment by ighilr** [comment]
Indeed, I hadn't paid attention to this "big" detail...

I will see with the Admins if it is still possible to integrate these fields. I hope to one day be able to see our data live via your report to make continuous improvement.

Thank you again for all :)

**Comment by nbrown02** [comment]
No worries - ok for me to close the issue?Sent from my iPhoneOn 10 Jun 2024, at 19:18, GitPassion ***@***.***> wrote:﻿
Indeed, I hadn't paid attention to this "big" detail...
I will see with the Admins if it is still possible to integrate these fields. I hope to one day be able to see our data live via your report to make continuous improvement.
Thank you again for all :)

**Comment by ighilr** [comment]
Yes, we can close the issue. Thanks :)

**Comment by nbrown02** [comment]
Thanks - let me know if you find a fix :)
