### ISSUE TITLE
Power BI Error

### ISSUE THREAD

**Issue by AJ-Greiner** [nbrown02/FlowViz-Jira#6]
Good morning, 
I have been trying to use FlowViz-Jira to connect my Project to Power Bi but keep getting this error saying (400) Bad Request 
![image](https://user-images.githubusercontent.com/107630512/174086330-745bcb4e-9296-4541-b9e7-62cef8acf2e2.png)

Thanks

**Comment by nbrown02** [comment]
Can you describe the project setup more to me (Scrum/Kanban) ?

Have you tried the URL in just the browser?

**Comment by AJ-Greiner** [comment]
I got it to work thanks.

**Comment by AJ-Greiner** [comment]
I ended up clearing everything and starting over and it connected.

Arthur (AJ) Greiner  |  Help Desk Supervisor
E: ***@***.******@***.***>  |  O: +1.516.283.8640

**Comment by nbrown02** [comment]
Thanks - well if you have feature requests please reach out. A feedback on the Atlassian marketplace also goes a long way if you find FlowViz useful!
